### ISSUE TITLE
How can i fix this error? I can't fix this error. 

### ISSUE THREAD

**Issue by bambarBrl** [eeglabdevelopers/eeglab#112]
help me!!!!!!!

EEGlab error in function subsasgn() at line 66:

Matrix index is out range for deletion.

if you think this is a bug, please submit a detailed description of how to reproduce the problem(and upload a small dataset) at https://github.com/sccn/eeglab/issues

**Comment by arnodelorme** [comment]
We need more context. What did you do to generate the error? Make sure you have the following tow options unset (in EEGLAB menu "File > Preferences").

"If set, use memory mapped array under Matlab 7.x. This may slow down some computation (beta)."
"If set, use the EEGLAB EEG object instead of the standard EEG structure (beta)."

Closing this bug. Please reopen the issue if you are able to provide more details.

Best wishes,

Arno

**Comment by arnodelorme** [comment]
Please reopen the issue if you are able to provide more details.

**Comment by arnodelorme** [comment]
Please reopen the issue if you are able to provide more details.

**Comment by bambarBrl** [comment]
![418](https://user-images.githubusercontent.com/59819123/72793633-ab3d8f80-3c75-11ea-9fc8-35e31b7811e5.png)
