### ISSUE TITLE
screen flashes when selecting data during channel scroll

### ISSUE THREAD

**Issue by mwalenski** [eeglabdevelopers/eeglab#12]
In Matlab 2018b, eeglab version 14.1.2, when viewing data with plot->channel scroll, the screen flashes whenever any data is selected with the mouse. it flashes once on first mouse click, then constantly while selecting data, and once more when the mouse button is released. This does not seem to affect functionality (the selected data can is apparently rejected fine), but it is more difficult to select data and is tough on the eyes. 

Thanks for any help with this!

**Comment by nucleuscub** [comment]
Hi @mwalenski, 
When you perform any of the described actions, the content of the figure is refreshed/regenerated, and that's the flicker you see. It may be more evident, depending on the video hardware you have. Since it does not affect the functionality, I do not think this is something we will address anytime soon. But thanks anyway for the heads up.
 R
