### ISSUE TITLE
Spectopo issue when signal processing toolbox is missing

### ISSUE THREAD

**Issue by NathiMagubane** [eeglabdevelopers/eeglab#129]
New to EEG Lab and Matlab in general, so I do not know how to explain the issue all too well. 
I have been trying to spectra map my dataset, but I am presented with the following error: 

EEGLAB error in function spectcomp() at line 941: 

Undefined function 'pwelch' for input arguments of type 'double' 

| OS version     | MacOS Mojave
| Matlab version | R2019b
| EEGLAB version | v2019.1

**Comment by zegamer** [comment]
Try to install Signal Processing Toolbox from the Add-on manager (Home > Add-on > Get Add-ons > Search for SPT > Install). It worked for me afterwards.

But even if you do not have SPT installed, it should use an alternative funtion spec() from the EEGLAB package, but it does not do that. So that is a  problem.

OS version: Windows 10
Matlab version: R2019b
EEGLAB version: v2019.1

**Comment by arnodelorme** [comment]
I agree. We will investigate.

**Comment by callen07** [comment]
Hi.  I have the same problem with the function findpeaks:

EEGLAB error in function findpeaks() at line 231:

Undefined function 'findpeaks' for input arguments of type 'double'

I have the SPT from Matlab, I asked them, because seems that the toolbox is not there, and I payed for that.  

>> which findpeaks -all  Running it before and after open eeglab we realized that EEGlab seems to remove some folders from your search path, because after open EEglab does not find any functions

This also affect another part of the analysis that I am pretending to do, so if you can help me to solve this, would be amazing.

**Comment by arnodelorme** [comment]
I have fixed the issue with pwelch. I have also added additional warnings.

**Comment by callen07** [comment]
What additional warnings?  Where I can find them, to solve my problem?
