### ISSUE TITLE
plugin_getweb fails

### ISSUE THREAD

**Issue by tiborauer** [eeglabdevelopers/eeglab#159]
### Description

`plugin_getweb` fails upon start because of the unusual description of `detect_spindles`

<br>
#### Steps to Reproduce

1. `eeglab`

<br>
#### Expected behavior:
Some menus items hidden. Use Preference menu to show them all.
eeglab: options file is ~/eeg_options.m
EEGLAB warning: there can be only one EEGLAB window, closing old one
Retrieving plugin versions from server...
Retreiving download statistics...
...
 

<br>
#### Actual behavior:
Some menus items hidden. Use Preference menu to show them all.
eeglab: options file is ~/eeg_options.m
EEGLAB warning: there can be only one EEGLAB window, closing old one
Retrieving plugin versions from server...
Retreiving download statistics...
Index exceeds the number of array elements (32).

Error in plugin_getweb (line 62)
    plugin(iRow).downloads = stats{2}(iRow);

Error in eeglab (line 915)
        pluginTmp = plugin_getweb('', pluginlist, 'newlist');

Error in eeglabClass/load (line 39)
            eeglab;
 

<br>
#### Versions

|   |   |
|----| ---- | 
| OS version     |CentOS Linux release 7.4.1708 (Core)
| Matlab version | R2019b
| EEGLAB version | v2019.1 (github)

**Comment by amydesroches** [comment]
Same issue here with Matlab R2020a, EEGLAB v 2019.1.

**Comment by arnodelorme** [comment]
Yes, we have solved the issue which was with a corrupted online plugin. We will make the code more robust. Thank you for reporting the problem.

Best wishes,

Arno

**Comment by yunshufan** [comment]
I encountered a similar issue today:
![image](https://user-images.githubusercontent.com/32801111/134440126-2635c1f5-8daf-4199-891e-91df21b43b44.png)
It wasn't there yesterday.
I'm using Matlab2021a and eeglab2019_1
Do I need to download and install the newest version of eeglab?

**Comment by b000z** [comment]
![eeglab error](https://user-images.githubusercontent.com/91285104/134565254-b89fb192-a54d-4315-9aa8-07d91b826ae8.png)

I encountered almost this problem yesterday with matlab r2020a and eeglab2019_1. I followed the instructions both https://github.com/sccn/eeglab/issues/20 and https://www.mathworks.com/matlabcentral/answers/130359-how-do-i-change-the-java-virtual-machine-jvm-that-matlab-is-using-on-windows which led me astray and caused matlab not to open. I found this and realized I may need to simply update eeglab. Just got v2021_1 and the issue is solved.

I cannot understand why this problem occurred. Have been using the current versions without any problem for more than 1 year, and all of a sudden, yesterday this error presented.
