### ISSUE TITLE
Incompatible with new format, trying old format and converting.

### ISSUE THREAD

**Issue by Nadia365** [eeglabdevelopers/eeglab#209]
I used eeg_regepochs() on a dataset, I save the output into a mat file and tried to load into EEG lab to visualize it but I got an error.
![error](https://user-images.githubusercontent.com/49712115/94545847-fe280780-0244-11eb-850a-b7e3917e49b1.JPG)

**Comment by arnodelorme** [comment]
Yes, this is not an EEGLAB dataset. It is just a Matlab file. Because it does not recognize the data format, EEGLAB think it might be an old dataset. However, it is just a Matlab array. See this tutorial for how to import Matlab files.

https://sccn.ucsd.edu/wiki/A01:_Importing_Continuous_and_Epoched_Data#Importing_a_random_Matlab_file
