### ISSUE TITLE
Trouble opening .MFF files

### ISSUE THREAD

**Issue by elannon** [eeglabdevelopers/eeglab#218]
### I am having difficulties opening .mff files with eeglab.  I get different errors at different times. I attached screenshots for both errors. 

I am using the GUI to load the files.
I am using the "latest version of EEGLAB" (as is reported in the eeglab opening process)
I am using the plug in "MFFMatlabIO" v3.5.

![image](https://user-images.githubusercontent.com/73861114/98271792-2b9f5980-1f45-11eb-98bd-c68c486a0269.png)
![image](https://user-images.githubusercontent.com/73861114/98273128-c2204a80-1f46-11eb-8460-e8b64eebcaaa.png)

Here is the link to the mff file and pics of error code

https://drive.google.com/drive/folders/15XXzd1d5LULgMjbqGC3eekpQxyxrZllr?usp=sharing

Thank you for your help

**Comment by arnodelorme** [comment]
The issue is with the special character in the event. When renaming the events ev1 and ev2 (see event file Events_ECI TCP-IP 55513.xml below after renaming events) I can import the file.

There is nothing much to do as the problem is with the Java library so Magstim/EGI need to fix it. https://www.egi.com/

<?xml version="1.0" encoding="UTF-8"?>
<eventTrack xmlns="http://www.egi.com/event_mff" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <name>ECI TCP-IP 55513</name>
    <trackType>STIM</trackType>
    <event>
        <beginTime>2019-03-28T13:43:11.571163-07:00</beginTime>
        <duration>1000</duration>
        <code>ev1</code>
        <label></label>
        <description></description>
        <sourceDevice>Multi-Port ECI</sourceDevice>
    </event>
    <event>
        <beginTime>2019-03-28T13:49:12.571163-07:00</beginTime>
        <duration>1000</duration>
        <code>ev2</code>
        <label></label>
        <description></description>
        <sourceDevice>Multi-Port ECI</sourceDevice>
    </event>
</eventTrack>
