### ISSUE TITLE
precompute component measures problem

### ISSUE THREAD

**Issue by tingyu653** [eeglabdevelopers/eeglab#308]
### Description
I used the eeglab STUDY. And when I tried to precompute component measures. 
I checked the ERPs and ERP image. And then I encountered the problem.
I put my data in the same folder and recreated the STUDY again, but still encountered the same problem.
![image](https://user-images.githubusercontent.com/85797007/121912185-f2dd2380-cd62-11eb-9684-923d6ffa6801.png)

#### Steps to Reproduce

1. [*First Step*]
2. [*Second Step*]
3. [*and so on...*]

#### Versions

|   |   |
|----| ---- | 
| OS version     | [*fill in*] |
| Matlab version | [*R2020a*] |
| EEGLAB version | [*v2020.0*] |

**Comment by arnodelorme** [comment]
This is because you have several datasets for the same subject and they have different ICA decompositions. This is only allowed if you have different sessions (days) for a given subject. Otherwise, if it is a recording on the same day or if the trials are split by condition, the ICA must be the same (you can select both datasets and run ICA on the two datasets).

**Comment by tingyu653** [comment]
I change the session of each dataset. But I still encounter the same problem.
![image](https://user-images.githubusercontent.com/85797007/121978929-ce616580-cdbb-11eb-94e9-161f359a8430.png)

**Comment by tingyu653** [comment]
Thanks, the problem is solved now.

**Comment by arnodelorme** [comment]
Good happy to know it works now.
