### ISSUE TITLE
arrow.m included with eeglab uses deprecated/undocumented functions and fails in MATLAB 2019a

### ISSUE THREAD

**Issue by JohnAtl** [eeglabdevelopers/eeglab#32]
### Description

The arrow.m included with eeglab uses an undocumented call that fails on MATLAB 2019a.

The new version of arrow [here](https://www.mathworks.com/matlabcentral/fileexchange/278-arrow) works correctly.

<br>
2019.0 (at least)

|   |   |
|----| ---- | 
| OS version     | macOS 10.14 |
| Matlab version | 2019a |
| EEGLAB version | 2019.0 |

**Comment by nucleuscub** [comment]
Hi @JohnAtl ,
 Thanks for bringing attention to this function. I can see this function is not being used in any EEGLAB function. Only Fieldtrip use it, but it uses its own copy. So, I guess we will discuss in our team if it is necessary keeping the function in EEGLAB.
 Otherwise, we will include it.
 Thanks,
R

**Comment by arnodelorme** [comment]
I have deprecated the function in EEGLAB.
