### ISSUE TITLE
error in function mcolon() at line82

### ISSUE THREAD

**Issue by benoalbe** [eeglabdevelopers/eeglab#354]
### Description
I'm using eeglab2021, Matlab 2020a and when I try to plot channel measures it appears this error when I'm going to run more two channels 
<img width="427" alt="Screenshot 2021-07-17 at 03 19 13" src="https://user-images.githubusercontent.com/87553083/126021152-56397f93-0439-417d-b9d2-a901e8b335a5.png">

[*Description of the bug or feature
Attach a link to Dropbox or Google Drive with screenshots and your data if possible.*]

<br>
#### Steps to Reproduce

1. [*First Step*]
2. [*Second Step*]
3. [*and so on...*]

<br>
#### Expected behavior:
[*What you expected to happen*]

<br>
#### Actual behavior:
[*What actually happened*]

<br>
#### Versions

|   |   |
|----| ---- | 
| OS version     | [*fill in*] |
| Matlab version | [*fill in*] |
| EEGLAB version | [*fill in*] |

**Comment by cll008** [comment]
Hi there, could you be more specific about how I would reproduce the bug? For example, which measures are you trying to plot? What OS are you on?

Looks like `mcolon` may have to be compiled by the user from [here](https://www.mathworks.com/matlabcentral/fileexchange/29854-multiple-colon). Not sure. I'll tag @MakotoMiyakoshi here since ARfitStudio also uses mcolon, maybe he has an idea.

**Comment by MakotoMiyakoshi** [comment]
I'm surprised to learn that EEGLAB uses mcolon... where exactly is it used?

**Comment by cll008** [comment]
Not sure, let's see if @benoalbe has more info on which study measure he was plotting...

**Comment by arnodelorme** [comment]
Hi Makoto, yes, this is an ARfitStudio problem (not a study problem). The user does not mention using a study.
