### ISSUE TITLE
Error in pop_epoch: dataset is empty

### ISSUE THREAD

**Issue by kathrinsadus** [eeglabdevelopers/eeglab#361]
### Description
During the preprocessing we encoutered a problem with the epoching of data. 
We receive an error indicating that the dataset is empty, although the epochs are present in our dataset.
<br>
#### Steps to Reproduce
We will glady provide the data set and code if needed. 
<br>
#### Expected behavior:
Data should be epoched.
<br>
#### Actual behavior:
The first three participants ran smoothly, but the preprocessing of the fourth dataset produced the following error:

pop_epoch():67 epochs selected
Epoching...
pop_epoch():67 epochs generated
pop_epoch(): checking epochs for data discontinuity
Error using pop_select (line 231)
Error: dataset is empty

Error in pop_epoch (line 407)
		EEG = pop_select(EEG, 'notrial', indexepoch);

We used the clean_raw_data function beforehand which produced multiple boundary events. 

We could process the dataset when we changed the extraction of boundary indices in the pop_epoch function
(line 397: boundaryindex = strmatch('boundary', { tmpevent.type }); -> we replaced strmatch thorugh contain)

However, we are still puzzled regarding the cause of this error.
<br>

#### Versions
|   |   |
|----| ---- | 
| Matlab version | 2021a |
| EEGLAB version | 2021.0 |

**Comment by arnodelorme** [comment]
The issue is likely that you are trying to extract long epochs and that you have a recurring artifact that clean_rawdata is catching (therefore inserting boundary events in the middle of your epochs). 

The use of contains is wrong in this context because it returns a boolean, not the indices of the boundary events.

Feel free to submit a dataset if you feel this does not answer your question.
