### ISSUE TITLE
Mobilab plugin xdf import

### ISSUE THREAD

**Issue by arnodelorme** [eeglabdevelopers/eeglab#382]
There is a path issue (xdfimport plugin not found)

**Comment by cll008** [comment]
https://github.com/sccn/mobilab/blob/b4520db251aa6a5d45b3903286e3a6bdf7290592/dataSourceXDF.m#L38

Looks like it can't find `load_xdf` here, which is nested in plugins/xdfimport<V#>/xdf

Maybe this error has been happening since https://github.com/sccn/mobilab/commit/4d620bf7d462f318fcdc89ddd76c3d1968eb595c

**Comment by cll008** [comment]
Note: PR was rejected but separate fix https://github.com/sccn/mobilab/commit/2a7f2e7994b62f50767528d9311f04808c55dc30 should address the problem
