### ISSUE TITLE
ERSP single trial normalization, different results with newtimef vs std_precompute

### ISSUE THREAD

**Issue by jacobsen-noelle** [eeglabdevelopers/eeglab#401]
### Description

Calculating ERSPs with single trial normalization produces different results with command line newtimef() than STUDY functions std_precompute(). 

Files: https://drive.google.com/drive/folders/100vnccz9CiaI7qDuWPaazaET3eyo5wII?usp=sharing

<br>
#### Steps to Reproduce

1. Calculate ERSP with newtimef
         CompNum = 14;
         [ersp,itc,powbase,times,freqs,erspboot,itcboot,tfdata] = ...
                    newtimef(EEG.icaact(CompNum,:,:), EEG.pnts, [EEG.xmin*1000 EEG.xmax*1000], EEG.srate, 'cycles',[3 0.8],...
                    'padratio', 2,'freqs',[3 128],'alpha', NaN, 'baseline',NaN,'basenorm','on','trialbase','full');
         close;
          figure;
          CompNum = [EEG.subject,'/IC ',num2str(CompNum)];
          tftopo(ersp,times,freqs,'logfreq','on','title', CompNum,'FontSize', 16);%'vert', timewarp.warpto

2.  Calculate ERSP with GUI in STUDY
      parameters entered: 'cycles',[3 0.8], 'padratio', 2,'freqs',[3 128],'alpha', NaN, 'baseline',NaN,'basenorm','on','trialbase','full'

<br>
#### Expected behavior:
The plots should be the same

<br>
#### Actual behavior:
The spectral power of the STUDY ERSPs are almost over 250x the range of power for newtimef ERSPs

<br>
#### Versions

|   |   |
|----| ---- | 
| OS version     | [Windows 64] |
| Matlab version | [2018a] |
| EEGLAB version | [2021.0] |

**Comment by cll008** [comment]
Hi @jacobsen-noelle thanks once again for a thorough bug report and the attached data. I think the issue here is related to the interaction of EEGLAB using different functions here for single subject (PSD & original ICA weights) vs study level (std_spec FFT & RMS ICA weights). See related issues #364 and #172; in particular [the last comment on 172](https://github.com/sccn/eeglab/issues/172#issuecomment-651468087) is a great summary. Unfortunately we haven't quite agreed on a theory or best practice (and this issue seems to resurface every few years, just like those surround channel location coordinate systems).
