### ISSUE TITLE
problem while loading data in eeglab

### ISSUE THREAD

**Issue by evastone97** [eeglabdevelopers/eeglab#426]
I am trying to upload a struct (mat file) that has been extracted from someone else and I want to load the data and be able to use EEGLAB but while loading the data I got some warnings and errors.

![image](https://user-images.githubusercontent.com/82998648/153899246-69739c82-d0bb-4daf-b997-5b283faa9614.png)
 
so in the end I only get one channel from my data, the sampling rate.

![image](https://user-images.githubusercontent.com/82998648/153899456-5cd3f686-0fe3-4db0-8abb-d3f303cd1aad.png)

Any feedback will be useful thank you in advance.

**Comment by amisepa** [comment]
Hi,

Can you please share the file?

**Comment by evastone97** [comment]
Hi, I have finally solved this issue. Thank you for your reply. Now I achieve to import everything also channel location etc, but the problem now is that I have to import also the events from the file that I have which is an array with the stimulus and responses. The problem here is that I tried to use the pop_select function but I have some errors there so if you can help me with that question it would be great!

**Comment by amisepa** [comment]
Ok, just attach the file here and I'll have a better idea of what you are trying to do.

**Comment by arnodelorme** [comment]
Thanks for looking into that Cedric.

**Comment by evastone97** [comment]
I can try to explain here: so I have successfully uploaded all the data except the events. (The data were in field trip format before and I have used the fieldtrip2eeglab function to be able to transfer them into EEGLAB format).
![image](https://user-images.githubusercontent.com/82998648/155844983-040ad609-515f-44de-857a-bb9638224110.png)


The problem now is that for the events I have a matrix with the stimulus types, the participant response, and the response time. How can I pass the events that I have in this format into eeglab? Thank you in advance.

**Comment by amisepa** [comment]
One nice way to deal with events is to use BIDS: https://eeglab.org/tutorials/04_Import/BIDS.html

Otherwise, you can convert them to EEGLAB format in a script. You need to have each event as a row in EEG.event, with its code name in EEG.event.type and its latency (i.e., timestamp in ms). 
When you are done, type EEG = eeg_checkset(EEG); to make sure the structure is compatible with EEGLAB and it should add the EEG.event.urevent column automatically. 

Here is an example, with conditions 1, 2, 4, 8 being each a stimulus category in an ERP study. Note you can also rename them with character strings if you want, with:
EEG = pop_selectevent(EEG, 'event',1,'renametype','stimulus1','deleteevents','off');
EEG = pop_selectevent(EEG, 'event',2,'renametype','response1','deleteevents','off');
etc...

![image](https://user-images.githubusercontent.com/58382227/156627515-949398cd-eb67-4d11-aeeb-ae690197d295.png)

Hope this helps,
Cedric

**Comment by arnodelorme** [comment]
@amisepa closing this bug report. Feel free to reopen if we are not complete.
