### ISSUE TITLE
problem with Eyetracker and EEG data Synchronization 

### ISSUE THREAD

**Issue by JuliaD89** [eeglabdevelopers/eeglab#452]
### Description
Error message, when trying to synchronize my EEG data with the Eyetracker data:

"EEGLAB error in function synchronize() at line 253:
Subscripted assignment dimension mismatch." 

I used the raw eeg data, thus, without any preprocessing (s. Dropbox). I don't know what's the problem, respectively how to solve it. Is it a bug or are my files not ok? 

Dropbox-Link:
https://www.dropbox.com/scl/fo/tute28bkecw5txgjvkwja/h?dl=0&rlkey=j5okfk0x3tknejtsmz2htou5c

<br>
#### Steps to Reproduce

I tried it with the single eeglab-files in Matlab as well as with eeglab itself. I also tried it with another file (participant) with the same error

1. The first step, creating a *.mat-file out of the *.txt-file, is fine
2. The second step for synchronizing the data produce the above mentioned error message

Info for the first and second step: 
The Start-event is 111 
The End-event is 200

We use SMI with the keyword MYKEYWORD

<br>
#### Expected behavior:
Succesful Synchronizing

<br>
#### Actual behavior:
[*What actually happened*]

<br>
#### Versions

|   |   |
|----| ---- | 
| OS version     | [*Windows 11*] |
| Matlab version | [*R2017b*] |
| EEGLAB version | [*v2021.1*] |

**Comment by arnodelorme** [comment]
Your eye tracking text file seems OK. I could not load the EEGLAB .set file because it is missing the associated .fdt file.
You should be able to use the EEGLAB menu "File > Import event info > From MATLAB array or ASCII file", select the text file, indicate 42 lines of header and then the name of your columns.

Not sure what the synchronize() function comes from
