### ISSUE TITLE
Issue about data import

### ISSUE THREAD

**Issue by jiadeL** [eeglabdevelopers/eeglab#472]
Hi,

I try to import my data which is in the EDF format, but the plugin shows me this. 

EEGLAB error in function edfannot2evt() at line 78:

Unable to perform assignment because the indices on the left side are not compatible with the size of the right side.

Does it mean something wrong about my raw? If so, is there anyway I can solve this problem？ My file is EDF format and I cannot upload to here.

Best
Jiade

**Comment by arnodelorme** [comment]
Would you mind sharing a data file?

**Comment by jiadeL** [comment]
I can't. The Github doesn't support .edf.

**Comment by arnodelorme** [comment]
You can zip the file. Or you can send me a personal email at arnodelorme@gmail.com

**Comment by arnodelorme** [comment]
@schloegl we cannot import this large EDF file with BIOSIG, would you mind to have a look https://drive.google.com/file/d/1v8_3sbCINIKhJsfpsIqF47_07SL3vXdy/view?usp=sharing

**Comment by arnodelorme** [comment]
@schloegl just in case you did not see the issue.

**Comment by Teuniz** [comment]
That "EDF" file is full of errors:  

1. the patient/subject field in the header is not properly formatted
2. the startdate in the header is not properly formatted
3. the starttime in the header is not properly formatted
4. the timestamps of the datarecords have illegal values
5. some samples have illegal values (they are outside the min/max range as specified in the header)

**Comment by jiadeL** [comment]
Thank you, @Teuniz

I wonder what kind of software you used to open EDF+ files. I tried to use LabChart, but it doesn't work. By the way, is there any way I can fix these errors?

**Comment by Teuniz** [comment]
> I wonder what kind of software you used to open EDF+ files. I tried to use LabChart, but it doesn't work. By the way, is there any way I can fix these errors?

I opened the file in an hexeditor and corrected the first three errors only, because they are located in the header and they can be corrected relatively easily (if you read carefully the EDF specification).  
Then I opened the file in EDFbrowser which raised some errors but they can be clicked away and that way I was able to view the signals.  
Ofcourse this is not a solution, the software that created the file needs to be fixed. I don't see another solution.

**Comment by arnodelorme** [comment]
Agreed that the software creating these corrupted EDF files need to be fixed. In the meantime, you can edit the Binary file and fix it by hand before importing it.

Also, there are 3 EDF importers in EEGLAB (BIOSIG, File-IO, and bdfimport). Maybe one of them works with your file.

**Comment by schloegl** [comment]
> @schloegl we cannot import this large EDF file with BIOSIG, would you mind to have a look https://drive.google.com/file/d/1v8_3sbCINIKhJsfpsIqF47_07SL3vXdy/view?usp=sharing

 edfannot2evt() is now fixed in such a way that you can load the file with biosig4matlab. The fixed version is available here: 
    https://git.ist.ac.at/alois.schloegl/code/-/commit/2a545617150fda9a00ba8e6a8e07670ed79b13b3

The example file is also readable mexSLOAD, and SigViewer. 

However, it complains about startdate and time, which is broken. As a consequence also the event positions are corrupted, too. 

If you have problems loading this large file, you are probably using a 32 bit version of Matlab or your OS. This will not work, as the conversion from int16 (EDF)  to double (Matlab), will require 1.2GBx4 = 4.8 GB RAM, which is larger then the 32 bit address range.
