### ISSUE TITLE
pop_delset

### ISSUE THREAD

**Issue by arnodelorme** [eeglabdevelopers/eeglab#517]
When there is only one dataset, it refuses to clear it

**Comment by dellabellagabriel** [comment]
If I understand correctly you're saying that `ALLEEG = pop_delset(ALLEEG, 1)` doesn't clear the fields when `ALLEEG` has one element? If that's the case I wasn't able to reproduce the bug. Maybe I misunderstood the problem.

**Comment by arnodelorme** [comment]
Good point. Maybe it works from the command line, but not from the GUI.

**Comment by dellabellagabriel** [comment]
The problem seems to be that the callback for the button "Delete dataset(s) from memory" eventually calls `eeglab redraw` which removes elements of `ALLEEG` that are empty:
```
% remove empty datasets in ALLEEG
while ~isempty(ALLEEG) && isempty(ALLEEG(end).data)
    ALLEEG(end) = [];
end
```
When there is a single element, `ALLEEG` will end up as a 1x0 struct which is eventually set equal to `EEG` in the `updatemenu` function:
```
if isempty(ALLEEG) && ~isempty(EEG) && all(arrayfun(@(eeg) ~isempty(eeg.data), EEG))
    ALLEEG = EEG;
end 
```
I see two ways of fixing this: either we don't remove cleared elements from `ALLEEG` or we don't set `ALLEEG` equal to `EEG` if it's empty. I'm not sure what the best approach would be in this case.

**Comment by arnodelorme** [comment]
Yes, good point. This is a special case. I think it is better to output an error message instead of hacking the code. There is an alternative in the File menu. I have committed some changes in commit 279ca9e5d

Feel free to look at other bug reports and even issue pull requests. Your contribution is most welcomed.

```
	error( [ 'Cannot delete dataset when there is only one of them. Restart EEGLAB' 10 'or use the menu item in the File menu to clear all datasets' ]);
```
