### ISSUE TITLE
Tutorial 

### ISSUE THREAD

**Issue by kr1st1na7** [eeglabdevelopers/eeglab#633]
The tutorial on this link https://eeglab.org/tutorials/04_Import/Importing_Event_Epoch_Info.html has you input 33 into the Event channel(s) box, but then produces an error reading 
"EEGLAB error in function pop_chanevent() at line 204:
Index in position 1 exceeds array bounds. Index must not exceed 32."
There are indeed 33 rows in the eegdata sample array, so I'm a bit confused, and as you can tell, I am new to EEGLAB and MATLAB in general. Thank you in advance for your help.

**Comment by arnodelorme** [comment]
@deepagupta will look into it.

**Comment by deepagupta** [comment]
Dear kr1st1na7,

Please follow the steps below in order to avoid the error:

1. Open MATLAB. Copy and paste the following code in your matlab command window:

`eegdata = rand(32, 256*100); % 32 channels of random activity (100 s sampled at 256 Hz).
eegdata(33,[10:256:256*100]) = 1; % simulating a stimulus onset every second
eegdata(33,[100:256:256*100]+round(rand*128)) = 2; % simulating reaction times about 500 ms after stimulus onsets
`

2. Open eeglab and then go to File -> Import data -> using  EEGLAB functions and plugins -> From ASCII/float file or Matlab array. Select matlab variable in the dropdown and type eegdata in the textbox next to it and type 256 in the textbox next to 'Time points per epoch (0-> continuous)' in the section 'Data sampling rate (Hz)'. Then click Ok.

3.  Type eeglab redraw in the command window just in case if needed. Then go to File->Import event info->From data channel and enter 33 followed by clicking ok as described in the tutorial and it should run ok.

I hope this is helpful. Please let us know if you are still running into any errors with the exact steps followed that led to that error.
Sincerely
Deepa

**Comment by arnodelorme** [comment]
I tried the tutorial and it worked for me.
