### ISSUE TITLE
Channel Spectra and Maps with ERP plots unexpected Frequency Maps

### ISSUE THREAD

**Issue by msseibel** [eeglabdevelopers/eeglab#65]
### Description
Bug described in the following pictures.

https://github.com/msseibel/EEGLAB
Images are called erp_bug.png and erp_bug_setting.png

Bug does only appear for the ERP selection. EEG selection works as expected.
#### Steps to Reproduce

1. Get dataset with 2 types of events
2. Plot -> Channel Spectra and Maps
3. Apply to ERP  see erp_bug_setting.png

#### Expected behavior:
Scalp maps for frequencies as specified in erp_bug_setting.png

#### Actual behavior:
Scalp maps for frequencies 0, 40/3, 80/3, 80/3

#### Versions
Plugins:
EEGLAB: adding "dipfit" v3.0 (see >> help eegplugin_dipfit) - new version 3.3 available
EEGLAB: adding "eegplugin_atisaio" v0.5 (see >> help eegplugin_atisaio)
EEGLAB: adding "firfilt" v2.1 (see >> help eegplugin_firfilt) - new version 2.4 available
|   |   |
|----| ---- | 
| OS version     | [Windows 10] |
| Matlab version | [2015] |
| EEGLAB version | [current version 2019] |

**Comment by nucleuscub** [comment]
@msseibel , This does not seem to be a bug in the code. When selecting  ERP, EEG or both, If processing data epochs, these options will work on either the mean single-trial 'EEG' spectra, the spectrum of the trial-average  'ERP', or plot 'BOTH' the EEG and ERP spectra. 
Given this, you should check first how the ERP's looks and then start from there to troubleshoot the results.
 Otherwise, I've checked with a sample dataset and all seems to be fine.
Moving to close this issue.
 R
