### ISSUE TITLE
newtimef.m: absolute power for wavelet and FFT

### ISSUE THREAD

**Issue by arnodelorme** [eeglabdevelopers/eeglab#85]
Dear eeglablist subscribers,

I have a question concerning the newtimef function.
As I want to calculate the absolute power of my data, I set the 'baseline'
parameter to 'NaN'.

Now, first thing that concerns me, I get totally different results using
either FFT or wavelets (freqs from 2-50Hz, FFT yielded values from -25 to
10, wavelet values from 36 to 48).

I'd appreciate any help, thanks in advance,

Ulrich Pomper

**Comment by arnodelorme** [comment]
@widmann would you mind to tell us your opinion on this?

**Comment by happymuzi** [comment]
The parameter pair 'baseline' and NaN only means no baseline correction. What you are looking for, I think, is the parameter pair 'scale' and 'abs'. This should be able to also control the output value. As the difference in FFT and wavelet method, my understanding is that they ought to differ since they are two different ways of time-frequency decomposition.

Hope you find this helpful.

**Comment by widmann** [comment]
Sorry, this is too unspecific. And I'm not an expert for newtimef, sorry.
Andreas
